import { Project } from "@/types/projectsType";

// Sample projects data
export const allProjects: Project[] = [
  {
    id: "fikirtepe-donusum",
    title: "Fikirtepe Kentsel Dönüşüm Projesi",
    category: "Kentsel Dönüşüm",
    location: "İstanbul, Kadıköy",
    year: "2023",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=500&fit=crop",
    description: "İstanbul'un en büyük kentsel dönüşüm projelerinden biri olan Fikirtepe'de 15.000 konutun yenilenmesi.",
    status: "ongoing",
  },
  {
    id: "izmir-deprem-konutlari",
    title: "İzmir Deprem Konutları",
    category: "Afet Yönetimi",
    location: "İzmir, Bayraklı",
    year: "2022",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=500&fit=crop",
    description: "2020 İzmir depremi sonrası inşa edilen depreme dayanıklı modern konut kompleksi.",
    status: "completed",
  },
  {
    id: "ankara-yesil-sehir",
    title: "Ankara Yeşil Şehir Projesi",
    category: "Sürdürülebilir Gelişim",
    location: "Ankara, Etimesgut",
    year: "2024",
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=800&h=500&fit=crop",
    description: "Sıfır karbon ayak izi hedefleyen, yenilenebilir enerji kaynaklarıyla desteklenen yaşam alanı.",
    status: "ongoing",
  },
  {
    id: "bursa-tarihi-koruma",
    title: "Bursa Tarihi Doku Koruma",
    category: "Tarihi Koruma",
    location: "Bursa, Osmangazi",
    year: "2021",
    image: "https://images.unsplash.com/photo-1555521893-3a0d8f9e4b3e?w=800&h=500&fit=crop",
    description: "UNESCO Dünya Mirası listesindeki Bursa tarihi merkezinin restorasyonu.",
    status: "completed",
  },
  {
    id: "antalya-sosyal-konut",
    title: "Antalya Sosyal Konut Projesi",
    category: "Sosyal Konut",
    location: "Antalya, Kepez",
    year: "2023",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=500&fit=crop",
    description: "Düşük gelirli aileler için inşa edilen 2.500 konutluk sosyal yaşam alanı.",
    status: "ongoing",
  },
  {
    id: "trabzon-akilli-sehir",
    title: "Trabzon Akıllı Şehir Altyapısı",
    category: "Akıllı Şehir",
    location: "Trabzon",
    year: "2025",
    image: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=800&h=500&fit=crop",
    description: "IoT sensörleri ve veri analitiği ile donatılmış modern şehir altyapısı projesi.",
    status: "planned",
  },
  {
    id: "konya-ekolojik-yerlesim",
    title: "Konya Ekolojik Yerleşim Alanı",
    category: "Sürdürülebilir Gelişim",
    location: "Konya, Selçuklu",
    year: "2022",
    image: "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&h=500&fit=crop",
    description: "Doğayla uyumlu, enerji verimli konutlardan oluşan ekolojik yaşam köyü.",
    status: "completed",
  },
  {
    id: "gaziantep-sanayi-donusum",
    title: "Gaziantep Sanayi Dönüşüm Projesi",
    category: "Kentsel Dönüşüm",
    location: "Gaziantep, Şehitkamil",
    year: "2024",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=500&fit=crop",
    description: "Eski sanayi bölgesinin karma kullanımlı modern yaşam alanına dönüştürülmesi.",
    status: "ongoing",
  },
  {
    id: "eskisehir-universite-konut",
    title: "Eskişehir Üniversite Konut Projesi",
    category: "Eğitim",
    location: "Eskişehir",
    year: "2021",
    image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800&h=500&fit=crop",
    description: "Öğrenciler için modern ve ekonomik yaşam alanları sunan konut kompleksi.",
    status: "completed",
  },
  {
    id: "mersin-liman-yenileme",
    title: "Mersin Liman Bölgesi Yenileme",
    category: "Kentsel Dönüşüm",
    location: "Mersin, Akdeniz",
    year: "2025",
    image: "https://images.unsplash.com/photo-1494522358652-f30e61e60942?w=800&h=500&fit=crop",
    description: "Tarihi liman bölgesinin turizm ve kültür merkezine dönüştürülmesi.",
    status: "planned",
  },
  {
    id: "kayseri-deprem-guclendirme",
    title: "Kayseri Yapı Güçlendirme Programı",
    category: "Afet Yönetimi",
    location: "Kayseri",
    year: "2023",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=500&fit=crop",
    description: "Mevcut binaların depreme karşı güçlendirilmesi için kapsamlı program.",
    status: "ongoing",
  },
  {
    id: "samsun-sahil-projesi",
    title: "Samsun Sahil Şeridi Projesi",
    category: "Kentsel Tasarım",
    location: "Samsun, Atakum",
    year: "2022",
    image: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&h=500&fit=crop",
    description: "Karadeniz kıyısında modern ve erişilebilir kamusal alan tasarımı.",
    status: "completed",
  },
];

export const categories = [
  "Tümü",
  "Kentsel Dönüşüm",
  "Afet Yönetimi",
  "Sürdürülebilir Gelişim",
  "Sosyal Konut",
  "Akıllı Şehir",
  "Tarihi Koruma",
];
