import type { ComponentMeta } from "../../../types";

export const meta: ComponentMeta = {
  slug: "story-viewer-01",
  name: "Story Viewer 01",
  category: "media",

  description:
    "Full-screen sequential story viewer — Radix Dialog modal with segmented progress, tap zones, keyboard nav, multi-story navigation, video composition via video-player-01, and a Subscribe<StoryViewerDelta> realtime contract.",
  context:
    "Use anywhere stories appear — Instagram-style modal viewer over a feed. Pairs with story-rail-01 (the seventh ship) which fires onItemClick(item, index); host opens <StoryViewer01 isOpen stories={...} initialStoryIndex={index} onClose={...} /> in response. The viewer's onStoryViewed(storyId) callback is what hosts wire back into railRef.current.markViewed(storyId) to clear the unread ring — viewer is fully decoupled from the rail. Image and video items both supported (video composes media/video-player-01). v0.1 ships click-outside + Escape close + arrow-key nav; framer-motion swipe-to-dismiss is the locked v0.2 adoption gate. Migration origin: kasder kas-social-front-v0 StoryViewer.tsx; eighth and final ship in the social-posts-system arc.",
  features: [
    "Radix Dialog modal — focus trap + portal + Escape + backdrop click free",
    "Mobile full-screen (h-dvh) / desktop centered portrait modal (md:h-175 md:w-100)",
    "Segmented progress bars (one per item; CSS `transition-[width]` fill; ARIA progressbar)",
    "Pause-preserving accumulator-based progress timer (fixes kasder's ~50ms drift per pause/resume)",
    "Item duration resolution: explicit `item.duration` → video metadata → default fallback",
    "Tap zones: left=prev item / middle=pause / right=next item (mobile + desktop)",
    "Desktop nav arrows: ← → between stories (story-level navigation)",
    "Keyboard nav: ArrowLeft/Right (item nav) + Space (pause) + Escape (close)",
    "Header: avatar + username + relative time + pause/play + mute (video only) + close",
    "video-player-01 composed for video items (cross-folder via registryDependencies)",
    "Subscribe<StoryViewerDelta> realtime contract: story-added / story-removed / item-added / item-removed / story-viewed",
    "ID-anchored cursor (NOT index-based) — story/item insertions / removals don't desync the cursor",
    "Always-uncontrolled state with `reset(next)` + `dispatch(action)` imperative escape hatches (matches story-rail-01 / post-card-01 / comment-thread-01)",
    "Cursor reset on (initialStoryIndex, isOpen) pair change — re-opening with same initialStoryIndex still goes back to item 0",
    "Forward-only `onStoryViewed` semantics (matches Instagram — backward navigation doesn't mark viewed)",
    "Auto-close at end of last story with synchronous `onAutoCloseAtEnd` callback before `onClose`",
    "renderItem slot for custom item types (Lottie, polls, sponsored, etc.)",
    "useStoryProgress + useStoryKeyboardNav exported standalone for advanced consumers",
    "i18n via 10-key labels object (defaults to English + native Intl.DateTimeFormat)",
    "a11y: DialogTitle (sr-only) + per-button aria-labels + per-segment role=progressbar with aria-valuenow",
    "v0.2.0 — Engagement overlay composing engagement-bar-01 v0.3.x (variant=stacked) — like + reaction (host-supplied kinds) + comment + share + kebab (bookmark removed in v0.3.0)",
    "v0.2.0 — Reply composer composing comment-thread-01 v0.2.1 CommentComposer with auto-pause-on-type + currentUser-gated visibility",
    "v0.2.0 — Role-aware mode (viewerMode='owner'|'viewer') + StoryViewerPermissions matrix + canPerformAction predicate (mirrors post-card-01 v0.3.0 resolver)",
    "v0.2.0 — Owner overlay: view-count chip (eager from story.viewerCount) + lazy viewers list panel (onLoadViewers slot; reuses LikersStrip)",
    "v0.2.0 — Kebab as 6th engagement-overlay item (Instagram-2024); fallback to header right cluster when disableEngagement",
    "v0.2.0 — Render slots: 1→7 (renderHeader/renderProgress/renderNavArrows/renderTapZones/renderEngagementOverlay/renderReplyComposer/renderOwnerOverlay)",
    "v0.2.0 — Disable opt-outs: 8 flags (disableTapZones/disableKeyboardNav/disableNavArrows/disableAutoClose/disableProgressBars/disableEngagement/disableReplyComposer/disableOwnerOverlay)",
    "v0.2.0 — Imperative handle: 7→13 methods (added setMuted/triggerLike/triggerReaction/triggerReply/triggerShare/openKebab)",
    "v0.2.0 — Polymorphic linkComponent + StoryItem.link CTA (bottom button; Q-V9 lock — sticker pattern deferred to v0.3 when story-sticker primitive lands)",
    "v0.2.0 — Long-press pause additive (Instagram-canonical mobile gesture; preserves v0.1 middle-tap-pause as desktop fallback; longPressThresholdMs prop tunable)",
    "v0.2.0 — F-S1 hygiene: VideoPlayer01 import switched to specific-file path",
    "v0.2.0 — Touch-target patch: header buttons 32×32 → 44×44 (WCAG 2.5.5 compliant)",
    "v0.2.1 — F-cross-13 viewer-shell patch: drop `showCloseButton={false}` prop (not in consumer's Radix dialog) + suppress close button via `[&>button.absolute]:hidden` CSS (works on both backends)",
    "v0.2.2 — Author tap-target additive: `onAuthorClick(story)` + polymorphic `authorComponent` (default `\"button\"` when handler set). Avatar + username strip becomes a real tap-target with hover/focus affordance; consumers can pass Next.js `<Link>` or `<a>` for href-based nav.",
    "v0.3.0 — Bookmark action removed from engagement overlay (stories are ephemeral; viewers don't bookmark stories. Owner-side `Save to highlights` stays in the kebab).",
    "v0.3.0 — Instagram-canonical comments panel: comment-icon tap opens a bottom-sheet (~62% viewer height) holding the host-supplied comments thread (typically `<CommentThread01 />` via `renderCommentsPanel`). Visual content above scales to 55% + translates up; tap anywhere on the shrunk visual closes the panel. Always-mounted (CommentThread01 draft state survives open/close). Story timer auto-pauses when panel open.",
    "v0.3.0 — DM input semantic clarified: the always-visible bottom `<ReplyComposer>` is the Direct Message channel to the story author (Instagram-canonical 'Reply to @user…'), NOT public comments. Public comments live in the new panel. `onAddReply` callback name preserved for back-compat.",
    "v0.3.0 — `disableComments?: boolean` opt-out — when set, comment-icon falls back to focusing the DM input (v0.2.x behavior).",
    "v0.3.1 — Share panel: share-icon tap opens an Instagram-canonical bottom-sheet holding the host-supplied share targets (typically `<ShareMenu />` from `@ilinxa/engagement-bar-01`) via `renderSharePanel`. `disableSharePanel` opt-out falls back to v0.2.x onShareStory-only behavior. Comments + share panels are mutually exclusive (opening one closes the other).",
    "v0.3.1 — `BottomSheet` part extracted (shared chrome for CommentsPanel + SharePanel). Drag-handle bar + heading row + scroll area + close button.",
    "v0.3.1 — Scroll fix: panel content area uses `overflow-y-auto overscroll-contain` (was `overflow-hidden`) so CommentThread01 + ShareMenu scroll properly on mobile.",
    "v0.3.1 — UI polish: backdrop dim (`bg-black/40`) behind shrunk visual when any panel is open; engagement icon sizes unified (kebab `h-5 → h-6` to match like/comment/share/reaction).",
    "v0.3.1 — DM input clickability fix: explicit `pointer-events-auto` + `z-[31]` + `right-16` (leaves space for right-side engagement overlay) so the always-visible Direct Message input wins focus reliably.",
  ],
  tags: ["story-viewer-01", "story", "viewer", "modal", "dialog", "media", "social"],

  version: "0.3.1",
  status: "alpha",
  createdAt: "2026-05-03",
  updatedAt: "2026-05-29",

  author: { name: "ilinxa" },

  dependencies: {
    shadcn: ["dialog", "avatar", "button"],
    npm: { "lucide-react": "^1.11.0" },
    internal: ["video-player-01", "engagement-bar-01", "comment-thread-01"],
  },

  related: ["story-rail-01", "video-player-01", "media-carousel-01", "post-card-01"],
};
